### ISSUE TITLE
peerjs.min.js Devtools peerjs.min.js.map error

### ISSUE THREAD

**Issue by khansikki** [peers/peerjs#681]
when the peerjs.min.js added through the script tag to html page i am getting this error in dev tools please assist how to avoid this. i am using peerjs version 1.2.0

DevTools failed to load SourceMap: Could not load content for http://localhost:8888/peerjs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by Florrr** [comment]
honestly.. I'm facing the exact same error in our implementation. But since it does not affect the code and everything still works - I just ignored it

**Comment by khansikki** [comment]
yes, code is working fine but error on fav peerjs is not fine :)

**Comment by khansikki** [comment]
in the end of peerjs.min.js file
removing the two slashes
// # sourceMappingURL=/peerjs.min.js.map
# sourceMappingURL=/peerjs.min.js.map

**Comment by afrokick** [comment]
fixed in 1.3.1

**Comment by compwiz21** [comment]
I'm using 1.3.1 and am getting this error

**Comment by Trevahok** [comment]
i’m using 1.3.1 and this error still exists

**Comment by eckel** [comment]
I'm using 1.3.2 now and also still get the error (in Safari on macOS)

**Comment by byhyakimaro** [comment]
I'm having the same problem
